### ISSUE TITLE
Cannot use the Cognito packages indicated

### ISSUE THREAD

**Issue by genifycom** [aws/aws-aspnet-cognito-identity-provider#181] opened 2020-11-15 22:26 UTC
Loading the Cognito packages indicated for this project gives:

Restoring packages for C:\Dev\SourceControl\Development\LambdaFunctions\TestAdmin\TestAdmin.csproj...
NU1107: Version conflict detected for AWSSDK.Core. Install/reference AWSSDK.Core 3.5.1 directly to project TestAdmin to resolve this issue. 
 TestAdmin -> Amazon.Extensions.CognitoAuthentication 2.0.0 -> AWSSDK.CognitoIdentityProvider 3.5.0.2 -> AWSSDK.Core (>= 3.5.1 && < 3.6.0) 
 TestAdmin -> Amazon.AspNetCore.Identity.Cognito 1.0.5 -> AWSSDK.Extensions.NETCore.Setup 3.3.100.1 -> AWSSDK.Core (>= 3.3.100 && < 3.4.0).
Package restore failed. Rolling back package changes for 'TestAdmin'.

**Comment by ashishdhingra** [comment] 2020-11-16 17:25
Duplicate of https://github.com/aws/aws-aspnet-cognito-identity-provider/issues/180

**Comment by ashishdhingra** [comment] 2020-11-18 17:02
#176

**Comment by ashishdhingra** [comment] 2020-12-04 21:12
Hi @genifycom,

Closing this as duplicate and we are working on getting a new version as part of other 2 issues.

Thanks,
Ashish

**Closed by ashishdhingra** 2020-12-04 21:12 UTC
Labels: bug, duplicate, module/cog-id-provider

**Comment by duaneking** [comment] 2021-04-20 23:25
This is still an issue and attempts to update fail.
