### ISSUE TITLE
Can't install latest version of nuget package: Amazon.Extensions.CognitoAuthentication

### ISSUE THREAD

**Issue by Mazekiller** [aws/aws-aspnet-cognito-identity-provider#180] opened 2020-11-15 03:17 UTC
## The Question
I am following this [guide](https://github.com/aws/aws-aspnet-cognito-identity-provider). I want to install the latest version of nuget package Amazon.Extensions.CognitoAuthentication (latest stable is 2.0.0)

But I get this error.

![image](https://user-images.githubusercontent.com/16949121/99162047-72681e80-26be-11eb-9c63-ab01f3c179b6.png)

I can actually install the nuget package as long as I don't also have Amazon.AspNetCore.Identity.Cognito installed. It seems that Amazon.Extensions.CognitoAuthentication v2.0.0 doesn't play nice with Amazon.AspNetCore.Identity.Cognito v1.0.5

I would like to know what would I lose if I choose to go with Amazon.Extensions.CognitoAuthentication v1.0.4 instead. I really want to use the identity implementation that already exists instead of having to build my own connection between cognito and asp.net identity.

### Environment
* Build Version: 2.0.0
* OS Info: Windows 10 Home
* Build Environment: Visual Studio
* Targeted .NET Platform:  .NET 5.0

---

This is a :question: general question

**Comment by ashishdhingra** [comment] 2020-11-16 17:25
Duplicate of https://github.com/aws/aws-aspnet-cognito-identity-provider/issues/181

**Comment by ashishdhingra** [comment] 2020-11-18 17:03
#176

**Comment by ashishdhingra** [comment] 2020-12-04 21:13
Closing this as duplicate of https://github.com/aws/aws-aspnet-cognito-identity-provider/issues/176.

**Closed by ashishdhingra** 2020-12-04 21:13 UTC
Labels: bug, duplicate, module/cog-id-provider
