### ISSUE TITLE
ETA on when production ready?

### ISSUE THREAD

**Issue by mrsuau627** [aws/aws-aspnet-cognito-identity-provider#15] opened 2018-12-02 16:15 UTC
Hi,

I'm looking to integrate with Cognito using Identity from a C# Web API and this looks like exactly what I need. I see that it's still in development. Is there an estimate on when this will be ready for production?

Thanks!

**Comment by vector-man** [comment] 2018-12-03 05:14
I'm also wondering about this. I'm trying to get my web app done within the next few months, and this would really speed up my development time.

**Comment by assyadh** [comment] 2018-12-03 23:02
Hi,

While I can not comment on any ETA at this point, most of the critical features are already available in the developer preview. 

I am actively working on it at the moment and would love to get any feedback!

Hamza

**Comment by assyadh** [comment] 2018-12-08 15:32
Hi mrsuau627,

Thanks for trying to integrate with the lib. 

These two constants were removed from one of the dependencies.

There is an open PR to fix the issue. It hasn't been merged to master yet:

https://github.com/aws/aws-aspnet-cognito-identity-provider/commit/f4724d583c000f0807a0ba41bca33ce58c4f0d0c

Can you try to merge that commit until I get that PR approved? You can also pull the PR branch (typed-exceptions-signinresult) 

I expect this to be fixed early next week. 

Thanks.

**Comment by assyadh** [comment] 2018-12-11 01:58
The issue is fixed now, you can pull master directly.

**Comment by assyadh** [comment] 2018-12-19 21:37
Hi,

The package is now available on NuGet and we are open to feedback during the developer preview phase.

https://www.nuget.org/packages/Amazon.AspNetCore.Identity.Cognito/

Please let us know what you think about the package!

**Closed by assyadh** 2018-12-19 21:37 UTC
