### ISSUE TITLE
User Registration Exception

### ISSUE THREAD

**Issue by josephd9** [aws/aws-aspnet-cognito-identity-provider#41] opened 2019-01-19 16:04 UTC
Thanks in advanced for helping!

During user registration I am getting an exception, "Operation Cancelled"  right here: var result = await _userManager.CreateAsync(user, Input.Password);

Is it possible I don't have something configured correctly in my user pool? I basically created the pool with all default values except I created a clientAPP. Also, I essentially copied the samples as they were. I'm extremely new to aws and authentication. 

![image](https://user-images.githubusercontent.com/32021618/51429096-cee87880-1bd0-11e9-91dd-2e51b9316a2f.png)

![image](https://user-images.githubusercontent.com/32021618/51429149-677ef880-1bd1-11e9-9892-24df436267b9.png)

**Comment by josephd9** [comment] 2019-01-19 18:51
I discovered two exceptions within the userManager:

'_signInManager.UserManager.Users' threw an exception of type 'System.NotSupportedException'

▶ | Session | '((Microsoft.AspNetCore.Http.DefaultHttpContext)_signInManager.Context).Session' threw an exception of type 'System.InvalidOperationException' | Microsoft.AspNetCore.Http.ISession {System.InvalidOperationException}

**Comment by jlwhitfill** [comment] 2019-01-21 16:59
IK had this issue about a week ago and posted my solution here:

https://github.com/aws/aws-aspnet-cognito-identity-provider/issues/38

Make sure you go to your Nuget packages and update everything if you are using Core 2.1.  The one I had to upgrade was:

`Microsoft.VisualStudio.Web.CodeGeneration.Design`

It then required me to install or upgrade a couple other packages.  When I did that everything started working correctly.

**Comment by josephd9** [comment] 2019-01-21 17:45
Thanks for the help! Sadly I have already done that and it's still not working. 

![image](https://user-images.githubusercontent.com/32021618/51490835-0e9a9600-1d72-11e9-8a9f-22bb81b97659.png)

**Comment by josephd9** [comment] 2019-01-21 17:55
I've also included the fix as mentioned here: https://stackoverflow.com/questions/37474309/timeouts-with-long-running-asp-net-mvc-core-controller-httppost-method

`      public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
                   .UseKestrel((o => { o.Limits.KeepAliveTimeout = TimeSpan.FromMinutes(10); }))
                   .UseStartup<Startup>();`

**Comment by assyadh** [comment] 2019-01-22 23:22
Hi @josephd9, I am working on implementing IQueryableUserStore which should solve: 

'_signInManager.UserManager.Users' threw an exception of type 'System.NotSupportedException'

I will be looking into the other issues shortly after.

**Comment by josephd9** [comment] 2019-01-23 14:42
Most totally excellent! Thanks!

**Comment by jlwhitfill** [comment] 2019-01-29 23:31
Will I be able to query this for users with a specific attribute (non custom of course)?  The reason I say this is that I am using the preferred_username as a sort of user tag and I want that to be unique, but since I use the email address as the username, that is the only thing I can make unique.  Would also be nice to make sure I am not creating users with the same phone number.

I tried calling the GetUsersForClaimAsync, passing in a specified attribute of preferred_username and its value as a claim but it replied back that it was Not Implemented.  Not sure if this is even possible.

I plan on having quite a few users and I would rather not have to pull back thousands of users to search in.  If we could Filter those users somehow by an attribute/claim that would be awesome

**Comment by assyadh** [comment] 2019-01-31 22:10
Hey @jlwhitfill , Cognito does not currently support querying custom attributes. There is no ETA on this support yet.
However, requesting Cognito standard attributes is possible. I can look into implementing GetUsersForClaimAsync just for this use case. It should cover your need.

**Comment by assyadh** [comment] 2019-01-31 22:11
Hi @josephd9, are you still seeing the Operation Cancelled Exception? If so, could you please share your stack trace. Also, if you are seeing this in Visual studio, do you have the AWS Toolkit for visual studio installed?

**Comment by jlwhitfill** [comment] 2019-01-31 22:20
Correct I know you cant query custom attributes, but I would like to query by standard ones like preferred_username and phone_number.  In my previous message  I tried calling the GetUsersForClaimAsync, passing in a specified attribute of preferred_username and its value as a claim but it replied back that it was Not Implemented. Not sure if this is even possible.  WIll I be able to query using the _signInManager.UserManager.Users with a filter?

**Comment by josephd9** [comment] 2019-01-31 22:59
> Hi @josephd9, are you still seeing the Operation Cancelled Exception? If so, could you please share your stack trace. Also, if you are seeing this in Visual studio, do you have the AWS Toolkit for visual studio installed?

Yup still seeing the same issue.

System.Net.Http.HttpClient.HandleFinishSendAsyncError(Exception e, CancellationTokenSource cts)
System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task<HttpResponseMessage> sendTask, HttpRequestMessage request, CancellationTokenSource cts, bool disposeCts)
System.Net.Http.HttpClient.GetStringAsyncCore(Task<HttpResponseMessage> getTask)
Amazon.Runtime.Internal.Util.AsyncHelpers+<>c__DisplayClass1_1<T>+<<RunSync>b__0>d.MoveNext()
Amazon.Runtime.Internal.Util.AsyncHelpers+ExclusiveSynchronizationContext.BeginMessageLoop() in AsyncHelpers.cs
Amazon.Runtime.Internal.Util.AsyncHelpers.RunSync<T>(Func<Task<T>> task) in AsyncHelpers.cs
Amazon.Util.AWSSDKUtils.DownloadStringContent(Uri uri, TimeSpan timeout, IWebProxy proxy) in AWSSDKUtils.cs
Amazon.Util.EC2InstanceMetadata.GetItems(string relativeOrAbsolutePath, int tries, bool slurp) in EC2InstanceMetadata.cs
Amazon.Util.EC2InstanceMetadata.get_IAMSecurityCredentials() in EC2InstanceMetadata.cs
Amazon.Runtime.DefaultInstanceProfileAWSCredentials.FetchCredentials() in DefaultInstanceProfileAWSCredentials.cs
Amazon.Runtime.DefaultInstanceProfileAWSCredentials.GetCredentials() in DefaultInstanceProfileAWSCredentials.cs
Amazon.Runtime.DefaultInstanceProfileAWSCredentials.GetCredentialsAsync() in DefaultInstanceProfileAWSCredentials.cs
Amazon.Runtime.Internal.CredentialsRetriever.InvokeAsync<T>(IExecutionContext executionContext) in CredentialsRetriever.cs
Amazon.Runtime.Internal.RetryHandler.InvokeAsync<T>(IExecutionContext executionContext)
Amazon.Runtime.Internal.RetryHandler.InvokeAsync<T>(IExecutionContext executionContext) in RetryHandler.cs
Amazon.Runtime.Internal.CallbackHandler.InvokeAsync<T>(IExecutionContext executionContext)
Amazon.Runtime.Internal.CallbackHandler.InvokeAsync<T>(IExecutionContext executionContext)
Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeAsync<T>(IExecutionContext executionContext)
Amazon.Runtime.Internal.MetricsHandler.InvokeAsync<T>(IExecutionContext executionContext)
Amazon.Extensions.CognitoAuthentication.CognitoUserPool.GetPasswordPolicyTypeAsync()
Amazon.AspNetCore.Identity.Cognito.CognitoPasswordValidator.ValidateAsync(UserManager<CognitoUser> manager, CognitoUser user, string password)
Amazon.AspNetCore.Identity.Cognito.CognitoUserManager<TUser>.ValidatePasswordInternal(TUser user, string password)
Amazon.AspNetCore.Identity.Cognito.CognitoUserManager<TUser>.CreateAsync(TUser user, string password, IDictionary<string, string> validationData)
Samples.Areas.Identity.Pages.Account.RegisterModel.OnPostAsync(string returnUrl) in Register.cshtml.cs
+
                    var result = await _userManager.CreateAsync(user, Input.Password);
Microsoft.AspNetCore.Mvc.RazorPages.Internal.ExecutorFactory+GenericTaskHandlerMethod.Convert<T>(object taskAsObject)
Microsoft.AspNetCore.Mvc.RazorPages.Internal.ExecutorFactory+GenericTaskHandlerMethod.Execute(object receiver, object[] arguments)
Microsoft.AspNetCore.Mvc.RazorPages.Internal.PageActionInvoker.InvokeHandlerMethodAsync()
Microsoft.AspNetCore.Mvc.RazorPages.Internal.PageActionInvoker.InvokeNextPageFilterAsync()
Microsoft.AspNetCore.Mvc.RazorPages.Internal.PageActionInvoker.Rethrow(PageHandlerExecutedContext context)
Microsoft.AspNetCore.Mvc.RazorPages.Internal.PageActionInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.RazorPages.Internal.PageActionInvoker.InvokeInnerFilterAsync()
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

**Comment by josephd9** [comment] 2019-01-31 22:59
Yes I have the took kit installed too

**Comment by josephd9** [comment] 2019-02-04 13:45
I'm not seeing one of the two errors inside the userManger object. 
▶ | Session | '((Microsoft.AspNetCore.Http.DefaultHttpContext)_signInManager.Context).Session' threw an exception of type 'System.InvalidOperationException' | Microsoft.AspNetCore.Http.ISession {System.InvalidOperationException}

Is gone. Still seeing '_signInManager.UserManager.Users' threw an exception of type 'System.NotSupportedException'

![image](https://user-images.githubusercontent.com/32021618/52211929-dc4c6680-2850-11e9-8a06-4050730de757.png)

**Comment by josephd9** [comment] 2019-02-06 13:09
Hello, sorry I'm a little confused does this update fix the issue I'm having with registration? Where the operation is cancelled in the OnPostAsync at this line: var result = await _userManager.CreateAsync(user, Input.Password); ??

**Comment by assyadh** [comment] 2019-02-06 15:52
Hi @josephd9, I am still working on it but haven't been able to repro the issue. Would you monde sharing a sample app that triggers the issue?

Please make sure to not include any secrets. 

Also, which version of net core are you running?

**Comment by josephd9** [comment] 2019-02-06 21:41
Sure thing. I'll have that for you shortly.

**Comment by jlwhitfill** [comment] 2019-02-07 16:52
@assyadh  Changes for 0.9.0.6 for the GetUsersForClaimAsync is working as expected.  Thank you!

**Comment by josephd9** [comment] 2019-02-11 17:37
Sorry for the delay. Here's a sample set up the same way as my own project with the same error. 
https://github.com/josephd9/CognitoTest2

While creating this I discovered that a few of the packages are showing this warning:
Detected package version outside of dependency constraint: Microsoft.AspNetCore.App 2.1.1 requires Microsoft.AspNetCore.Razor.Language (>= 2.1.1 && < 2.2.0) but version Microsoft.AspNetCore.Razor.Language 2.2.0 was resolved.

I've attempted to updated all my packages to 2.20 and updated my netcore to 2.2 but then I get build errors. I've tried downgrading everything to 2.1.1 and I don't get this warning but I still can't register a user. So I've left all the packages at the highest version I can put them.

**Comment by ricardoalbarracin** [comment] 2019-02-13 14:43
I have the same problem, is there any known solution for this error?

**Comment by jlwhitfill** [comment] 2019-02-13 22:10
Make sure you are using Core 2.1.  Do not use 2.2 or 1.x.  Also make sure all your nuget packages are up to date.  When I updated all of mine it started working

**Comment by assyadh** [comment] 2019-02-14 00:11
@josephd9, this does not seem related to your sample app, as it does not trigger the issue in my case when targeting 2.1 and 2.2.

It looks like a 'retrieving the aws credentials' issue.

**Comment by josephd9** [comment] 2019-02-14 12:59
Could it be that my cognito identity/user pools are not set up correctly?

**Comment by assyadh** [comment] 2019-02-14 20:58
Hey @josephd9 , I think I have the root cause. You do not have a default development profile for the .NET SDK to find. As this library is built on top of the SDK, it needs some credentials.

So two ways to do this: you can install the aws cli and then run aws configure in a command shell,

Or you can set up a development profile in the AWS Toolkit and name it default:

https://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-creds.html

The credentials would be picked up in a production environment in the instance metadata.

Please let me know if this fixes the issue, i will add this to the onboarding documentation.

**Comment by josephd9** [comment] 2019-02-14 22:43
I created the default user and added it to the toolkit but did not see any change in the problem. I found the link you provided to be slightly confusing. Is that a list of steps I need to take in addition to using the toolkit or does the content of the url replace the toolkit if I choose not to use it? I also selected 'no permission boundaries' for my dev account but the group i set it to also has no policies set. Could any of that be impacting me?

**Comment by assyadh** [comment] 2019-02-14 23:26
I was referring to the "Using the SDK Store" section of the link. When injecting instance of the .NET SDK clients, your development environment relies on specific credential files available. 

The quickest way to create them is by creating a "default" profile (with the name "default") in the AWS toolkit. You can do this by going into View -> AWS Explorer -> click on the little + button and create a profile named "default"

**Comment by flgatormike** [comment] 2019-02-15 00:49
Wow, this is frustrating. First I tried creating a profile in powershell as administrator and got errors like "script not enabled" and "module not enabled" and googled to try to find solutions. Then I tried installing the AWS toolkit and get "not all privileges or groups referenced are assigned to the caller" And I'm assuming if I spend hours to get this working, I would also need spend time getting a profile created on my production server as well?

**Comment by assyadh** [comment] 2019-02-15 00:52
This setup is only required while developing with the SDK for. NET. 

On a production environment, credentials are retrieved using the ec2 instance metadata for example (ie the IAM role attached to the ec2 instance)

**Comment by flgatormike** [comment] 2019-02-15 01:29
Is there a way to use the SDK without creating the profile? I am not having any luck with that.

**Comment by assyadh** [comment] 2019-02-15 01:42
You can also inject your own instances of Cognito clients as specified in the Readme. This can be done with specifying an access key and a secret key. However this is not recommended and you should rely on IAM roles with just enough permissions.

**Comment by flgatormike** [comment] 2019-02-15 02:21
I tried creating my own instances like below and I still get the same error when I try to log in:

OperationCanceledException: The operation was canceled.
System.Net.Http.HttpClient.HandleFinishSendAsyncError(Exception e, CancellationTokenSource cts)



            var region = RegionEndpoint.GetBySystemName("us-east-1");
            AmazonCognitoIdentityProviderClient provider = new AmazonCognitoIdentityProviderClient(region);
            CognitoUserPool pool = new CognitoUserPool("us-east-1_abcdefg", "6i5cxxxxxxxflk1t", provider, "26ubcaxxxxxxxxxxxxxxxxxxxxxxgj");

            services.AddSingleton<IAmazonCognitoIdentityProvider>(provider);
            services.AddSingleton<CognitoUserPool>(pool);

            services.AddCognitoIdentity();

**Comment by assyadh** [comment] 2019-02-15 02:23
You are missing the access key and secret key if you want to use it like that when instantiating the
AmazonCognitoIdentityProviderClient


Whitout providing these, it will go the same route (credential file)

**Comment by flgatormike** [comment] 2019-02-15 12:37
Ok, it is working now. I just want to test and if everything works OK I can get the default profile working.
Thanks!

**Comment by josephd9** [comment] 2019-02-15 13:35
Man this is frustrating. I can't seem to get this working. 
Here's what I've done. I must be missing something or not understanding.

1) I used the AWS Explorer to add a user called Default (I created a user in IAM first).
2) I added the below code to startup. 

        ` var region = RegionEndpoint.GetBySystemName("us-east-1");
            AmazonCognitoIdentityProviderClient provider = new 
          AmazonCognitoIdentityProviderClient("AXXXXXXXXXXXXXXQ", 
          "KXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXa", region);
            CognitoUserPool pool = new CognitoUserPool("us-east-1_XXXXX", "4XXXXXXXXXXXm", provider, 
           "2XXXXXXXXXXXXXXXXXXXXXXXXXXXXm");

            services.AddSingleton<IAmazonCognitoIdentityProvider>(provider);
            services.AddSingleton<CognitoUserPool>(pool);

            services.AddCognitoIdentity();`

**Comment by flgatormike** [comment] 2019-02-15 14:17
Did you give your user necessary permissions? For testing, I added policy "AmazonCognitoPowerUser" to my user and then it worked.

**Comment by flgatormike** [comment] 2019-02-15 16:47
Just curious, does the CognitoUserManager method CreateAsync allow you to pass additional attributes? For example, I have "family_name" and "given_name" as required. The method CreateAsync has a parameter "validationData" which I thought I could pass those, but it doesn't look like that works. Should I not make those fields required in Cognito and just require them on my website, and then just update the new user with those attributes?

**Comment by assyadh** [comment] 2019-02-15 16:50
You can add them on the CognitoUser parameter through the Attributes property. They have to exist on the pool but it's not necessary to flag them as mandatory. This is ip to you and your needs. 

The validationData parameter on CreateAsync is there if you want to pass data to a lambda presignup trigger for instance.

**Comment by flgatormike** [comment] 2019-02-15 18:18
Thanks for all your help. That works great. Just one more question and it is also related to User Registration so I will post it here. After the user is registered, it is successful, but when "SignInAsync" is called, I get the error below. The user gets created successfully in Cognito so not sure why I get "user does not exist"


var result = await _userManager.CreateAsync(user, Input.Password);
if (result.Succeeded)
{
        await _signInManager.SignInAsync(user, isPersistent: false);
        return RedirectToPage("./ConfirmAccount");
}


UserNotFoundException: User does not exist.
Amazon.Runtime.Internal.HttpErrorResponseExceptionHandler.HandleException(IExecutionContext executionContext, HttpErrorResponseException exception) in HttpErrorResponseExceptionHandler.cs, line 60

CognitoServiceException: Failed to retrieve roles for the Cognito User
Amazon.AspNetCore.Identity.Cognito.CognitoUserStore<TUser>.GetRolesAsync(TUser user, CancellationToken cancellationToken)

**Comment by jlwhitfill** [comment] 2019-02-15 19:20
Are you using email as the primary userid?  I had this issue because of that  and added the code below prior to the SignInAsync (which I got rid of as I dont want the user logged in prior to confirmation, but in any case add:

      `user = await _userManager.FindByEmailAsync(<users email address)`

then pass that user to the SignInASsnc method and it works.

**Comment by flgatormike** [comment] 2019-02-15 19:26
Thanks. That makes sense and your solution works perfectly.

**Closed** 2019-02-18 18:12 UTC
Labels: investigation

**Comment by josephd9** [comment] 2019-02-18 20:32
My AWS account was disabled. I'm working to correct it. It may take a minute for me to get back to this issue.

**Comment by assyadh** [comment] 2019-02-18 20:34
It most likely has to do with the issue I opened in your repo.

**Comment by josephd9** [comment] 2019-02-19 03:50
You opened in issue in my aws repo?

**Comment by josephd9** [comment] 2019-02-19 03:52
oh for the...oh the hell did i make that kind of mistake!

**Comment by assyadh** [comment] 2019-02-19 05:04
You can install this so it doesn't happen again:

https://github.com/awslabs/git-secrets

**Comment by josephd9** [comment] 2019-02-19 14:06
thanks! *smh* such a bone headed mistake. I'm almost fixed up now. I'll get back to implementing these fixes for my cognito issue in a few days. I haven't tried the suggestion to give my user permissions.

**Comment by josephd9** [comment] 2019-02-20 13:58
YYYYYEEESSS!!! It's working for me! I needed to add the cognitopoweruser policy. I'm sure there is much more work to do with fine tuning and proper permissions but for now it works! Thanks so much for the help! Now I'm off to learn how to protect my secrets. lol

**Comment by assyadh** [comment] 2019-02-22 19:19
No problem,

The version 0.9.0.11 now exposes a UserManager.GetUsersAsync() method to retrieve the lists of users in the pool, as well as filtering options.

See: https://github.com/aws/aws-aspnet-cognito-identity-provider/blob/master/src/Amazon.AspNetCore.Identity.Cognito/CognitoUserManager.cs#L670

The UserManager.Users property should not be used.

**Comment by jpmock** [comment] 2019-03-11 23:34
Hi, I believe I am having this issue as well.  I am using the sample Account app and when I try to register a user I get the following:

`TaskCanceledException: A task was canceled.
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)`

I am pretty sure my pool is setup correctly and I have all the proper configuration in the appsettings.json

**Comment by iApartmentDPL** [comment] 2019-04-27 15:08
hi , in my case for registration after using access and secret access key i just change
  user.Attributes.Add(CognitoAttributesConstants.Email, Input.Email) to 
 user.Attributes.Add("email", Input.Email);

**Comment by DragonMastery** [comment] 2019-09-10 10:05
Please update the sample application because it does not function due to this issue.
